<a href="https://colab.research.google.com/github/EllenBonafin/machine-learning/blob/main/APM_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IMPORTANDO OS CALSSIFICADORES 


In [ ]:
from sklearn.neighbors import KNeighborsClassifier # KNN
from sklearn.tree import DecisionTreeClassifier, export_graphviz # Árvore de decisão
from sklearn.naive_bayes import GaussianNB # Naive Bayes
from sklearn.svm import SVC # SVM
from sklearn.neural_network import MLPClassifier # MLP

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import statistics
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

IMPORTANDO A BASE DE DADOS

In [ ]:
df = pd.read_csv('/content/Lithuanianok.csv')
df_param = pd.DataFrame(df, columns=df.columns[:-1])

In [ ]:
#Previa da base de dados
df.head()

A1        A2  Class
0   9.654958  4.002121      1
1  10.778071  3.215585      1
2   5.267417 -9.959199      1
3   7.845224  4.954154      1
4   7.035757 -5.301141      1

In [ ]:
print(df_param.shape)

(2000, 2)


DATA SET

In [ ]:
#Divisão da base original : primeira metade para cada, 50% para o treino e 50% para os dois restantes
x_training, x_remaining, y_training, y_remaining = train_test_split(df_param, df['Class'], test_size=0.5, shuffle=True, stratify=df['Class'])

#Realiza a divisão do restante (metade para cada, 50% para teste e 50% para validação)
x_validation, x_test, y_validation, y_test = train_test_split(x_remaining, y_remaining, test_size=0.5, shuffle=True, stratify=y_remaining)
print('Treino')
print(x_training.shape) #50% 
print(np.unique(y_training, return_counts=True))
print(' ')
print('Validação')
print(x_validation.shape) #25% 
print(np.unique(y_validation, return_counts=True))
print(' ')
print('teste')
print(x_test.shape) #25%
print(np.unique(y_test, return_counts=True))

Treino
(1000, 2)
(array([1, 2]), array([500, 500]))
 
Validação
(500, 2)
(array([1, 2]), array([250, 250]))
 
teste
(500, 2)
(array([1, 2]), array([250, 250]))


ALCANÇANDO OS MELHORES PARAMETROS

KNN


In [ ]:
#KNN Não ponderado
print('KNN NÃO PONDERADO')
# Inicializa um array vazio onde sera gravado a acuracia
acuracia = []

for i in range (1,21):
  knn = KNeighborsClassifier(n_neighbors=i, weights='uniform')
  knn.fit(x_training, y_training)
  prev = knn.predict(x_validation)
  
  # Grava a acuracia com o k = i na posicao i+1
  acuracia.append(accuracy_score(y_validation, prev))

#best_Value vai Gravar o valor que apresentara o melhor resuldado
best_value = np.argmax(acuracia)+1 
# Mostra o valor que apresentou a maior acuracia
print("Melhor valor K = ", best_value)
print("Acuracia com o K=", best_value, " = ", acuracia[np.argmax(acuracia)])
print(acuracia)
print("")
  
#KNN Ponderado pelo inverso da distância euclidiana
print('KNN PONDERADO PELO VALOR DA DISTANCIA EUCLIDIANA')
# Inicializa um array vazio onde sera gravado a acuracia
acuracia = []

for i in range (1,21):
  knn = KNeighborsClassifier(n_neighbors=i, metric='euclidean', weights='distance')
  knn.fit(x_training, y_training)
  prev = knn.predict(x_validation)
  
  # Grava a acuracia com o k = i na posicao i+1
  acuracia.append(accuracy_score(y_validation, prev))

# Grava o valor que apresentou o melhor resuldado
best_value = np.argmax(acuracia)+1  
# Mostra o valor que apresentou a maior acuracia
print(" O Melhor K = ", best_value) 
print("Acuracia com o K=", best_value, " = ", acuracia[np.argmax(acuracia)])
print(acuracia)
print("")

KNN NÃO PONDERADO
Melhor valor K =  18
Acuracia com o K= 18  =  0.97
[0.958, 0.962, 0.968, 0.968, 0.968, 0.968, 0.966, 0.966, 0.966, 0.966, 0.966, 0.966, 0.968, 0.964, 0.968, 0.966, 0.968, 0.97, 0.968, 0.97]

KNN PONDERADO PELO VALOR DA DISTANCIA EUCLIDIANA
 O Melhor K =  6
Acuracia com o K= 6  =  0.966
[0.958, 0.958, 0.964, 0.964, 0.962, 0.966, 0.964, 0.964, 0.962, 0.962, 0.96, 0.962, 0.964, 0.964, 0.964, 0.964, 0.964, 0.964, 0.964, 0.964]



ARVORE DE DECISÃO

1.MELHORES PARAMETROS


---



In [ ]:
# Árvore sem poda
ad = DecisionTreeClassifier()
ad.fit(x_training, y_training) 
prev = ad.predict(x_validation)

print("No = ", ad.tree_.node_count)
# Pega a densidade da árvore sem poda
depth = ad.get_depth() 
# Adiciona um para rodar um a mais da densidade maxima
depth = depth + 1 
# Inicializa um array vazio onde sera gravado a acuracia
acuracia = []

# Comparando todas as árvores possiveis
for i in range (1, depth):
  ad = DecisionTreeClassifier(max_depth = i)
  ad.fit(x_training, y_training) 
  prev = ad.predict(x_validation)
  # Grava a taxa de erro com o max_depth = i na posicao i+1
  acuracia.append(accuracy_score(y_validation, prev))
  print("No = ", ad.tree_.node_count)

melhor_max_depth = np.argmax(acuracia)+1  # Grava o valor que apresentou o melhor resuldado
print(acuracia)
print("MELHOR DENSIDADE = ", melhor_max_depth) # Mostra o valor que apresentou a maior acuracia
print("A ACURACIA COM A MELHOR DENSIDADE =", melhor_max_depth, " = ", acuracia[np.argmax(acuracia)])

No =  75
No =  3
No =  7
No =  15
No =  25
No =  39
No =  53
No =  61
No =  67
No =  69
No =  73
No =  75
[0.8, 0.866, 0.932, 0.948, 0.954, 0.96, 0.96, 0.964, 0.964, 0.964, 0.962]
MELHOR DENSIDADE =  8
A ACURACIA COM A MELHOR DENSIDADE = 8  =  0.964


2.CALSSIFICADOR COM OS MELHORES PARAMETROS OBTIDOS


In [ ]:
# Inicializa o classificador com o melhor parametro
ad = DecisionTreeClassifier(max_depth = 3)
ad.fit(x_training, y_training) 
prev = ad.predict(x_test)

# Avalia a precisão
print(accuracy_score(y_test, prev))
print(confusion_matrix(y_test, prev))

0.924
[[219  31]
 [  7 243]]


3.VIZUALIZAÇÃO DA ARVORE

In [ ]:
# é Necessario ter a instalado para exibir a árvore graficamente
!apt-get install python-pydot
!pip install pydotplus

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  python-pyparsing
Suggested packages:
  python-pyparsing-doc
The following NEW packages will be installed:
  python-pydot python-pyparsing
0 upgraded, 2 newly installed, 0 to remove and 39 not upgraded.
Need to get 71.7 kB of archives.
After this operation, 347 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 python-pyparsing all 2.2.0+dfsg1-2 [52.1 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic/universe amd64 python-pydot all 1.2.3-1 [19.6 kB]
Fetched 71.7 kB in 1s (140 kB/s)
Selecting previously unselected package python-pyparsing.
(Reading database ... 155335 files and directories currently installed.)
Preparing to unpack .../python-pyparsing_2.2.0+dfsg1-2_all.deb ...
Unpacking python-pyparsing (2.2.0+dfsg1-2) ...
Selecting previously unselected package python-pydot.
Preparing to unp

In [ ]:
!pip install --upgrade scikit-learn==0.20.3

     |████████████████████████████████| 5.4 MB 3.5 MB/s 
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.0.2
    Uninstalling scikit-learn-1.0.2:
      Successfully uninstalled scikit-learn-1.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.4 requires scikit-learn>=1.0.0, but you have scikit-learn 0.20.3 which is incompatible.
imbalanced-learn 0.8.1 requires scikit-learn>=0.24, but you have scikit-learn 0.20.3 which is incompatible.


In [ ]:
from sklearn.externals.six import StringIO
from IPython.display import Image
import pydotplus

dot_data = StringIO()
export_graphviz(ad, out_file=dot_data)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
Image(graph.create_png())

ModuleNotFoundError: ignored

NAIVE BASE


In [ ]:
# Inicializa o classificador
nb = GaussianNB()

# Treina o classificador
nb.fit(x_training, y_training)
prev = nb.predict(x_test)

# Avalia a precisão
print(accuracy_score(y_test, prev))
print(confusion_matrix(y_test, prev))

0.892
[[217  33]
 [ 21 229]]


SVM

ENCONTRANDO OS MELHORES PARAMETROS

In [ ]:
#SVM Polinomial
print('SVM Polinomial')
# Inicializa um array vazio onde será gravado a acuracia
acuracia = []

# Testa vários degree no classificador
for i in range(1,21):
  svm_polinomial = SVC(C=i, kernel='poly')
  svm_polinomial.fit(x_training, y_training)
  prev = svm_polinomial.predict(x_validation)
  # Grava a taxa de erro com o c = i na posicao i+1
  acuracia.append(accuracy_score(y_validation, prev))

melhor_c = (np.argmax(acuracia)+1) # Grava o valor que apresentou o melhor resuldado
print(acuracia) # Mostra as acuracias
print("Melhor C = ", melhor_c) # Mostra o valor que apresentou a maior acuracia
print("Acuracia com o C =", melhor_c, " = ", acuracia[np.argmax(acuracia)])
print('------------------------------------------------------------------')
# SVM Radial
print('SVM Radial')
acuracia = []

for i in range(1,20):
  svm_radial = SVC(C=i, kernel='rbf')
  svm_radial.fit(x_training, y_training)
  prev = svm_radial.predict(x_validation)
  # Grava a taxa de erro com o degree = i na posicao i+1
  acuracia.append(accuracy_score(y_validation, prev))

melhor_c = (np.argmax(acuracia)+1) # Grava o valor que apresentou o melhor resuldado
print(acuracia) # Mostra as taxas de erro
print("Melhor C = ", melhor_c) # Mostra o valor que apresentou a maior acuracia
print("Acuracia com o C =", melhor_c, " = ", acuracia[np.argmax(acuracia)])

SVM Polinomial
[0.958, 0.956, 0.96, 0.962, 0.96, 0.96, 0.96, 0.96, 0.96, 0.96, 0.96, 0.96, 0.96, 0.96, 0.96, 0.96, 0.96, 0.96, 0.96, 0.96]
Melhor C =  4
Acuracia com o C = 4  =  0.962
------------------------------------------------------------------
SVM Radial
[0.964, 0.966, 0.966, 0.968, 0.968, 0.966, 0.964, 0.964, 0.964, 0.964, 0.964, 0.964, 0.964, 0.964, 0.964, 0.964, 0.964, 0.964, 0.964]
Melhor C =  4
Acuracia com o C = 4  =  0.968


MLP

In [ ]:
acuracia = []

# Inicializa o classificador
for i in range (1,10):
  for j in range (1,10):
    for k in range (1,10):
      mlp = MLPClassifier(max_iter=(k*200) , hidden_layer_sizes=(j*50), learning_rate_init=((i)/10) )
      mlp.fit(x_training, y_training)
      prev = mlp.predict(x_validation)
      
      # Grava a acuracia com o k = i na posição i+1
      acuracia.append(accuracy_score(y_validation, prev))

melhor_param = str(np.argmax(acuracia)+111)
print(acuracia)

melhor_max_iter = int(melhor_param[0])*200 # Grava os parametros que apresentaram o melhor resultado
melhor_hidden_layer = int(melhor_param[1])*50
melhor_learning_rate = int(melhor_param[2])/10
print("Melhor max iter = ", melhor_max_iter) # Mostra o valor que apresentou a maior acuracia
print("Melhor hidden layer = ",melhor_hidden_layer)
print("Melhor learning rate = ",melhor_learning_rate)
print("Acuracia com os melhores parametros = ", acuracia[np.argmax(acuracia)])

[0.942, 0.958, 0.956, 0.946, 0.962, 0.952, 0.948, 0.96, 0.96, 0.964, 0.944, 0.964, 0.962, 0.96, 0.956, 0.956, 0.952, 0.958, 0.944, 0.948, 0.962, 0.94, 0.966, 0.958, 0.96, 0.944, 0.966, 0.952, 0.95, 0.948, 0.966, 0.95, 0.968, 0.934, 0.964, 0.954, 0.958, 0.94, 0.956, 0.964, 0.948, 0.896, 0.954, 0.962, 0.958, 0.97, 0.964, 0.952, 0.958, 0.946, 0.954, 0.952, 0.97, 0.958, 0.968, 0.966, 0.956, 0.956, 0.962, 0.96, 0.952, 0.966, 0.944, 0.96, 0.95, 0.956, 0.942, 0.958, 0.97, 0.952, 0.944, 0.94, 0.97, 0.97, 0.964, 0.95, 0.938, 0.94, 0.962, 0.962, 0.948, 0.938, 0.96, 0.954, 0.966, 0.966, 0.966, 0.948, 0.934, 0.956, 0.938, 0.95, 0.97, 0.95, 0.968, 0.958, 0.97, 0.948, 0.952, 0.96, 0.964, 0.942, 0.952, 0.96, 0.95, 0.958, 0.966, 0.97, 0.942, 0.948, 0.96, 0.966, 0.968, 0.958, 0.958, 0.956, 0.954, 0.952, 0.958, 0.958, 0.942, 0.956, 0.96, 0.954, 0.968, 0.954, 0.944, 0.948, 0.96, 0.968, 0.964, 0.946, 0.956, 0.966, 0.96, 0.932, 0.96, 0.946, 0.956, 0.922, 0.944, 0.948, 0.936, 0.934, 0.942, 0.946, 0.94, 0.96

O melhor MLP foi com os seguintes parametros:

- Melhor épocas de treino = 400
- Melhor camadas escondidas = 300
- Melhor taxa de aprendizagem = 0.8

AVALIANDO OS CALSSIFICADORES

In [ ]:
acuraciaknn = []
acuraciaad = []
acuracianb = []
acuraciasvm = []
acuraciamlp = []

soma = []
produto = []


for i in range(1,21):

  #Realiza a divisão (metade para cada, 50% para treino e 50% para restante)
  x_treino, x_restante, y_treino, y_restante = train_test_split(df_param, df['Class'], test_size=0.5, shuffle=True, stratify=df['Class'])

  #Realiza a divisão do restante (metade para cada, 50% para teste e 50% para validação)
  x_validacao, x_teste, y_validacao, y_teste = train_test_split(x_restante, y_restante, test_size=0.5, shuffle=True, stratify=y_restante)
    
  # KNN
  # Inicializa o classificador com o melhor parametro
  knn = KNeighborsClassifier(n_neighbors = 2)
  knn.fit(x_treino, y_treino)
  prev = knn.predict(x_teste)
  
  acuraciaknn.append(accuracy_score(y_teste, prev))

  # Avalia a precisão
  clasiffication_knn = classification_report(y_teste, prev)
  knn_prev = prev  

  # Árvore de decisão
  # Inicializa o classificador com o melhor parametro
  ad = DecisionTreeClassifier(max_depth = 3)
  ad.fit(x_treino, y_treino) 
  prev = ad.predict(x_teste)
  acuraciaad.append(accuracy_score(y_teste, prev))

  # Avalia a precisão
  clasiffication_ad = classification_report(y_teste, prev)
  ad_prev = prev

  # NB
  # Inicializa o classificador
  nb = GaussianNB()
  nb.fit(x_treino, y_treino)
  prev = nb.predict(x_teste)

  acuracianb.append(accuracy_score(y_teste, prev))

  # Avalia a precisão
  clasiffication_nb = classification_report(y_teste, prev)
  nb_prev = prev

  # SVM
  svm_radial = SVC(C=2, kernel='rbf', probability=True)
  svm_radial.fit(x_treino, y_treino)
  prev = svm_radial.predict(x_teste)

  acuraciasvm.append(accuracy_score(y_teste, prev))
  
  # Avalia a precisão
  clasiffication_svm = classification_report(y_teste, prev)
  svm_prev = prev
 
  # MLP
  mlp = MLPClassifier(max_iter=200 , hidden_layer_sizes=50, learning_rate_init=0.4)
  mlp.fit(x_treino, y_treino)
  prev = mlp.predict(x_teste)

  acuraciamlp.append(accuracy_score(y_teste, prev))

  
  # Avalia a precisão
  clasiffication_mlp = classification_report(y_teste, prev)
  mlp_prev = prev

  svm_proba = svm_radial.predict_proba(x_teste)
  knn_proba = knn.predict_proba(x_teste)
  ad_proba = ad.predict_proba(x_teste)
  mlp_proba = mlp.predict_proba(x_teste)
  nb_proba = nb.predict_proba(x_teste)


print("KNN")
print("")
print("Acuracias = ", acuraciaknn)
print("Maior acuracia = ", acuraciaknn[np.argmax(acuraciaknn)])
print("Desvio padrão = ", statistics.pstdev(acuraciaknn))
print("Media geometrica = ", statistics.mean(acuraciaknn))
print(clasiffication_knn)
print("")
print("-----------------------------------------------------------------------")
print("")
print("Árvore de decisão")
print("")
print(acuraciaad)
print("Maior acuracia = ", acuraciaad[np.argmax(acuraciaad)])
print("Desvio padrão = ", statistics.pstdev(acuraciaad))
print("Media geometrica = ", statistics.mean(acuraciaad))
print(clasiffication_ad)
print("")
print("-----------------------------------------------------------------------")
print("")
print("Naive Bayes")
print("")
print(acuracianb)
print("Maior acuracia = ", acuracianb[np.argmax(acuracianb)])
print("Desvio padrão = ", statistics.pstdev(acuracianb))
print("Media geometrica = ", statistics.mean(acuracianb))
print(clasiffication_nb)
print("")
print("-----------------------------------------------------------------------")
print("")
print("SVM")
print("")
print(acuraciasvm)
print("Maior acuracia = ", acuraciasvm[np.argmax(acuraciasvm)])
print("Desvio padrão = ", statistics.pstdev(acuraciasvm))
print("Media geometrica = ", statistics.mean(acuraciasvm))
print(clasiffication_svm)
print("")
print("-----------------------------------------------------------------------")
print("")
print("MLP")
print("")
print(acuraciamlp)
print("Maior acuracia = ", acuraciamlp[np.argmax(acuraciamlp)])
print("Desvio padrão = ", statistics.pstdev(acuraciamlp))
print("Media geometrica = ", statistics.mean(acuraciamlp))
print(clasiffication_mlp)

KNN

Acuracias =  [0.956, 0.968, 0.962, 0.972, 0.952, 0.964, 0.954, 0.942, 0.956, 0.962, 0.956, 0.958, 0.972, 0.972, 0.968, 0.956, 0.966, 0.956, 0.964, 0.964]
Maior acuracia =  0.972
Desvio padrão =  0.007549834435270757
Media geometrica =  0.961
              precision    recall  f1-score   support

           1       0.95      0.98      0.96       250
           2       0.98      0.94      0.96       250

    accuracy                           0.96       500
   macro avg       0.96      0.96      0.96       500
weighted avg       0.96      0.96      0.96       500


-----------------------------------------------------------------------

Árvore de decisão

[0.922, 0.938, 0.924, 0.938, 0.904, 0.93, 0.914, 0.918, 0.914, 0.926, 0.934, 0.914, 0.944, 0.918, 0.924, 0.916, 0.932, 0.922, 0.912, 0.928]
Maior acuracia =  0.944
Desvio padrão =  0.009991996797437418
Media geometrica =  0.9236
              precision    recall  f1-score   support

           1       0.89      0.97      0.93      

In [ ]:
acuracias_regra_produto = []
prod1 = []
prod2 = []
for i in range(20):
    prev_produto = []
    prod1 = prod2 = 0
    for j in range(75):
        prod1 = knn_proba[i][j][0] * ad_proba[i][j][0] * svm_prev[i][j][0] * mlp_prev[i][j][0] * nb_prev[i][j][0]
        prod2 =  knn_proba[i][j][1] * ad_proba[i][j][1] * svm_proba[i][j][1] * mlp_proba[i][j][1] * nb_proba[i][j][1]
        if prod1 >= prod2:
            pred_produto.append(1)
        else:
            pred_produto.append(2)
    acuracias_regra_produto.append(accuracy_score(y_teste,pred_produto))

print("Acurácias múltiplos classificadores com regra do produto:")
print(*acuracias_regra_produto, sep=' | ')
print("Maior acurácia = ",acuracias_regra_soma[np.argmax(acuracias_regra_produto)])
media_regra_produto = statistics.mean(acuracias_regra_produto)
print("Média das acurácias = ",media_regra_produto)
desviop_regra_produto = statistics.pstdev(acuracias_regra_produto)
print("Desvio padrão das acurácias = ",desviop_regra_produto)

IndexError: ignored