<a href="https://colab.research.google.com/github/EllenBonafin/machine-learning/blob/main/ML3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importando bibliotecas

In [1]:
import sklearn
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression 
from sklearn.neural_network import MLPRegressor
#from yellowbrick.regressor import ResidualsPlot
from sklearn import datasets # dataset exemplo
from sklearn.model_selection import train_test_split #divisao da base
from sklearn.svm import SVR #SVR
from sklearn.metrics import mean_squared_error #RMSE
from math import sqrt #RAIZ QUADRADA
from sklearn.ensemble import RandomForestRegressor #RF
import statsmodels.formula.api as sm

import numpy as np

from sklearn.datasets import load_boston
boston_dataset = load_boston()


/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, s

In [2]:
boston = pd.DataFrame(boston_dataset.data, columns=boston_dataset.feature_names)
boston['MEDV'] = boston_dataset.target #adiciona a coluna medv
boston_parm = pd.DataFrame(boston, columns=boston.columns[:])
boston.head()
boston

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [3]:
X = pd.DataFrame(np.c_[boston['LSTAT'], boston['RM']], columns = ['LSTAT','RM'])
Y = boston['MEDV']

Divisão dos dados

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3, random_state=5)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(354, 2)
(152, 2)
(354,)
(152,)


In [5]:
lin_model = LinearRegression()
lin_model.fit(X_train, Y_train)

LinearRegression()

Coeficiente de Correlação (R) e Coeficiente de Determinação (R^2)

In [6]:
X = boston.iloc[:,0].values    #CRIM: Taxa de criminalidade per capita por cidade
Y = boston.iloc[:,1].values    #ZN: Proporção de terrenos residenciais zoneados para lotes acima de 25.000 pés quadrados
Z = boston.iloc[:,2].values    #INDUS: Proporção de acres de negócios não varejistas por cidade 
D = boston.iloc[:,3].values    #CHAS: Variável dummy Charles River (= 1 se o trato limita o rio; 0 caso contrário)
E = boston.iloc[:,4].values    #NOX: Concentração de óxido nítrico (partes por 10 milhões)
F = boston.iloc[:,5].values    #RM: Número médio de cômodos por residência
G = boston.iloc[:,6].values    #AGE: Proporção de unidades ocupadas pelos proprietários construídas antes de 1940
H = boston.iloc[:,7].values    #DIS: Distâncias ponderadas a cinco centros de emprego de Boston
I = boston.iloc[:,8].values    #RAD: Índice de acessibilidade a rodovias radiais
J = boston.iloc[:,9].values    #TAX: Taxa de imposto predial de valor total por $ 10.000
K = boston.iloc[:,10].values   #PTRATIO: Proporção aluno-professor por cidade
L = boston.iloc[:,11].values   #B: 1.000(Bk — 0,63 )², onde  Bk é a proporção de [pessoas de ascendência afro-americana] por cidade
M = boston.iloc[:,12].values   #LSTAT: Percentual de status mais baixo da população
S = boston.iloc[:,13].values   #MEDV: Valor médio das casas ocupadas pelos proprietários em US$ 1.000 #SAIDA


correlacao = np.corrcoef(X,S)
print ("CC em X:\n",correlacao) #R
determinacao= correlacao*correlacao
print ("CD em X:\n",determinacao) #R^2

print("\n")
correlacao = np.corrcoef(Y,S)
print ("CC em Y:\n",correlacao)
determinacao= correlacao*correlacao
print ("CD em Y:\n",determinacao) #R^2

print("\n")
correlacao = np.corrcoef(Z,S)
print ("CC em Z:\n",correlacao)#R
determinacao= correlacao*correlacao
print ("CD em Z:\n",determinacao) #R^2

print("\n")
correlacao = np.corrcoef(D,S)
print ("CC em D:\n",correlacao)#R
determinacao= correlacao*correlacao
print ("CD em D:\n",determinacao) #R^2

print("\n")
correlacao = np.corrcoef(E,S)
print ("CC em E:\n",correlacao)#R
determinacao= correlacao*correlacao
print ("CD em E:\n",determinacao) #R^2

print("\n")
correlacao = np.corrcoef(F,S)
print ("CC em F:\n",correlacao)#R
determinacao= correlacao*correlacao
print ("CD em F:\n",determinacao) #R^2

print("\n")
correlacao = np.corrcoef(G,S)
print ("CC em G:\n",correlacao)#R
determinacao= correlacao*correlacao
print ("CD em G:\n",determinacao) #R^2

print("\n")
correlacao = np.corrcoef(H,S)
print ("CC em H:\n",correlacao)#R
determinacao= correlacao*correlacao
print ("CD em H:\n",determinacao) #R^2

print("\n")
correlacao = np.corrcoef(I,S)
print ("CC em I:\n",correlacao)#R
determinacao= correlacao*correlacao
print ("CD em I:\n",determinacao) #R^2

print("\n")
correlacao = np.corrcoef(J,S)
print ("CC em J:\n",correlacao)#R
determinacao= correlacao*correlacao
print ("CD em J:\n",determinacao) #R^2

print("\n")
correlacao = np.corrcoef(K,S)
print ("CC em K:\n",correlacao)#R
determinacao= correlacao*correlacao
print ("CD em K:\n",determinacao) #R^2

print("\n")
correlacao = np.corrcoef(L,S)
print ("CC em L:\n",correlacao)#R
determinacao= correlacao*correlacao
print ("CD em L:\n",determinacao) #R^2

print("\n")
correlacao = np.corrcoef(M,S)
print ("CC em M:\n",correlacao)#R
determinacao= correlacao*correlacao
print ("CD em M:\n",determinacao) #R^2

CC em X:
 [[ 1.         -0.38830461]
 [-0.38830461  1.        ]]
CD em X:
 [[1.         0.15078047]
 [0.15078047 1.        ]]


CC em Y:
 [[1.         0.36044534]
 [0.36044534 1.        ]]
CD em Y:
 [[1.         0.12992084]
 [0.12992084 1.        ]]


CC em Z:
 [[ 1.         -0.48372516]
 [-0.48372516  1.        ]]
CD em Z:
 [[1.         0.23399003]
 [0.23399003 1.        ]]


CC em D:
 [[1.         0.17526018]
 [0.17526018 1.        ]]
CD em D:
 [[1.         0.03071613]
 [0.03071613 1.        ]]


CC em E:
 [[ 1.         -0.42732077]
 [-0.42732077  1.        ]]
CD em E:
 [[1.         0.18260304]
 [0.18260304 1.        ]]


CC em F:
 [[1.         0.69535995]
 [0.69535995 1.        ]]
CD em F:
 [[1.         0.48352546]
 [0.48352546 1.        ]]


CC em G:
 [[ 1.         -0.37695457]
 [-0.37695457  1.        ]]
CD em G:
 [[1.         0.14209474]
 [0.14209474 1.        ]]


CC em H:
 [[1.         0.24992873]
 [0.24992873 1.        ]]
CD em H:
 [[1.         0.06246437]
 [0.06246437 1.     

Regressão linear múltipla

In [31]:
X = X.reshape(-1,1)
modeloX = LinearRegression()
modeloX.fit(X,S)

Y = Y.reshape(-1,1)
modeloY = LinearRegression()
modeloY.fit(Y,S)

Z = Z.reshape(-1,1)
modeloZ = LinearRegression()
modeloZ.fit(Z,S)

print ("b em X: ", modeloX.intercept_)
print ("a em X: ", modeloX.coef_)

print ("b em Y: ", modeloY.intercept_)
print ("a em Y: ", modeloY.coef_)

print ("b em Z: ", modeloZ.intercept_)
print ("a em Z: ", modeloZ.coef_)

#  plt.scatter(X,S)
#  plt.xlabel("CRIM")
#  plt.ylabel("MEDV")
#  plt.plot(X, modeloX.predict(X),color='red')

# plt.scatter(Y,S)
# plt.xlabel("ZN")
# plt.ylabel("MEDV")
# plt.plot(Y, modeloY.predict(Y), color='pink')

#plt.scatter(Z,S)
#plt.xlabel("INDUS")
#plt.ylabel("MEDV")
#plt.plot(Z, modeloZ.predict(Z),color='green')

#plt.scatter(D,S)
#plt.xlabel("CHAS")
#plt.ylabel("MEDV")
#plt.plot(Z, modeloZ.predict(Z),color='black')

#plt.scatter(E,S)
#plt.xlabel("NOX")
#plt.ylabel("MEDV")
#plt.plot(Z, modeloZ.predict(Z),color='red')

#plt.scatter(F,S)
#plt.xlabel("RM")
#plt.ylabel("MEDV")
#plt.plot(Z, modeloZ.predict(Z),color='red')

#plt.scatter(G,S)
#plt.xlabel("AGE")
#plt.ylabel("MEDV")
#plt.plot(Z, modeloZ.predict(Z),color='red')

#plt.scatter(H,S)
#plt.xlabel("DIS")
#plt.ylabel("MEDV")
#plt.plot(Z, modeloZ.predict(Z),color='red')

#plt.scatter(I,S)
#plt.xlabel("RAD")
#plt.ylabel("MEDV")
#plt.plot(Z, modeloZ.predict(Z),color='red')

#plt.scatter(J,S)
#plt.xlabel("TAX")
#plt.ylabel("MEDV")
#plt.plot(Z, modeloZ.predict(Z),color='red')

#plt.scatter(K,S)
#plt.xlabel("PTRATIO")
#plt.ylabel("MEDV")
#plt.plot(Z, modeloZ.predict(Z),color='red')

#plt.scatter(L,S)
#plt.xlabel("B")
#plt.ylabel("MEDV")
#plt.plot(Z, modeloZ.predict(Z),color='red')

#plt.scatter(M,S)
#plt.xlabel("LSTAT")
#plt.ylabel("MEDV")
#plt.plot(Z, modeloZ.predict(Z),color='red')



ValueError: ignored

SVR

In [23]:
svr = SVR(kernel='rbf', C=100, gamma=0.1, epsilon=.1).fit(X,S)
saida = svr.predict(X)

print("SVR")
rms = sqrt(mean_squared_error(saida, S))
print ("Raiz do erro quadratico medio:",rms)

SVR
Raiz do erro quadratico medio: 0.2470702154608933


MLP

In [25]:
regr = MLPRegressor(hidden_layer_sizes=(5,5,5),max_iter=500).fit(X, S)
saida = regr.predict(X)
print("MLP")
rms = sqrt(mean_squared_error(saida, S))
print ("Raiz do erro quadratico medio:",rms)

MLP
Raiz do erro quadratico medio: 0.2704344416760387


RF

In [26]:
X = boston.iloc[:,0:3].values    #KM
S = boston.iloc[:,3].values    #Saida
RFR = RandomForestRegressor(max_depth=2, random_state=0).fit(X,S)
saida = RFR.predict(X)

print("RANDOM FOREST R")
rms = sqrt(mean_squared_error(saida, S))
print ("Raiz do erro quadratico medio:",rms)

RANDOM FOREST R
Raiz do erro quadratico medio: 0.2395107606530617
